version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:3.8.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ${RABBITMQ_VOLUME:-queue_storage}:/var/lib/rabbitmq

volumes:
  queue_storage:
