apiVersion: v1
kind: Service
metadata:
  name: checkout-job
  labels:
    app: checkout-job
    tier: backend
spec:
  ports:
    - port: 7000
      targetPort: 7000
  # Replace with the IP of your minikube node / master node
#  externalIPs:
#    - 172.17.0.2
  selector:
    app: checkout-job
    tier: backend
