apiVersion: v1
kind: Service
metadata:
  name: mgmt
  labels:
    app: mgmt
    tier: backend
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: main
  # Replace with the IP of your minikube node / master node
#  externalIPs:
#    - 172.17.0.2
  selector:
    app: mgmt
    tier: backend
