apiVersion: v1
kind: Service
metadata:
  name: order-api
  labels:
    app: order-api
    tier: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  # Replace with the IP of your minikube node / master node
#  externalIPs:
#    - 172.17.0.2
  selector:
    app: order-api
    tier: backend
