apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
spec:
  selector:
    matchLabels:
      app: payment-api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-api
        tier: backend
    spec:
      containers:
      - name: container-payment-api
        image: $DOCKERHUB_USER/payment-service:latest
        ports:
          - containerPort: 8100
        env:
          - name: MONGOPAYMENT_CS
            value: "mongodb://paymentservice:ps89fsj&2#@mongo-payment:27018/admin"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
