apiVersion: v1
kind: Service
metadata:
  name: payment-api
  labels:
    app: payment-api
    tier: backend
spec:
  ports:
    - port: 8100
      targetPort: 8100
  # Replace with the IP of your minikube node / master node
#  externalIPs:
#    - 172.17.0.2
  selector:
    app: payment-api
    tier: backend
