kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-order-pvc
spec:
  storageClassName: manual
  volumeName: mongo-order-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
