apiVersion: v1
kind: Service
metadata:
  name: mongo-payment
  labels:
    app: mongo-payment
    role: master
    tier: backend
spec:
#  type: NodePort
  ports:
    - port: 27018
      targetPort: 27017
      name: core
  # Expose ports through the IP below. Another option is to use NodePort (or port-forward, or ELB)
#  externalIPs:
#    - 172.17.0.2
  selector:
    app: mongo-payment
    role: master
    tier: backend
