kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-payment-pvc
spec:
  storageClassName: manual
  volumeName: mongo-payment-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
