version: "3.7"

services:

  payment-mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
        - payment-storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: paymentservice
      MONGO_INITDB_ROOT_PASSWORD: ps89fsj&2#
    restart: on-failure
    networks:
      - payment-network

  payment-mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: paymentservice
      ME_CONFIG_MONGODB_ADMINPASSWORD: ps89fsj&2#
      ME_CONFIG_MONGODB_SERVER: payment-mongo
    networks:
      - payment-network

volumes:
  payment-storage:

networks:
  payment-network:
