# Module: http
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-http.html

- module: http
  metricsets:
    - json
  period: 1s
  hosts: ["localhost:7000"]
  namespace: "shopping_cart"
  path: "/metrics"
  #body: ""
  method: "GET"
  #username: "user"
  #password: "secret"
  #request.enabled: false
  #response.enabled: false
  json.is_array: true
  #dedot.enabled: false

- module: http
  #metricsets:
  #  - server
  host: "localhost"
  port: "8080"
  enabled: false
  #paths:
  #  - path: "/foo"
  #    namespace: "foo"
  #    fields: # added to the the response in root. overwrites existing fields
  #      key: "value"
