kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbit-pvc
spec:
  storageClassName: manual
  volumeName: rabbit-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
