apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        role: master
        tier: backend
    spec:
      containers:
        - name: rabbitmqcontainer
          image: rabbitmq:3.8.8-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbit-pvc
