version: "3.7"

services:

  order-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
        - order-storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: orderservice
      MONGO_INITDB_ROOT_PASSWORD: s89fsj&2#
    restart: on-failure
    networks:
      - order-network

  order-mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: orderservice
      ME_CONFIG_MONGODB_ADMINPASSWORD: s89fsj&2#
      ME_CONFIG_MONGODB_SERVER: order-mongo
    networks:
      - order-network

volumes:
  order-storage:

networks:
  order-network:
