version: "3.7"

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
        - storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: orderservice
      MONGO_INITDB_ROOT_PASSWORD: s89fsj&2#
    restart: on-failure

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: orderservice
      ME_CONFIG_MONGODB_ADMINPASSWORD: s89fsj&2#
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  storage:
