kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elk-pvc
spec:
  storageClassName: manual
  volumeName: elk-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

